image:
  file: .gitpod.dockerfile

tasks:
  - name: Installation Task
    init: npm install
    command: npm start

  - name: mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data


  - name: atlas shell
    init: brew install mongodb-atlas

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-browser

  - name: dbpath
    port: 27017

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - ms-toolsai.jupyterdocs/introduction/getting-started/quickstart
    - mongodb.mongodb-vscode
