image:
  file: .gitpod.dockerfile

tasks:
  - name: Installation Task
    init: |
      pip install -r requirements.txt # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
  #   gp sync-done pip-install

  # - name: script
  #   init: gp sync-await pip-install  # wait for bb to finish
  #   command:  python test.py

  - name: mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

  # - name: mongo shell
  #   init: |
  #     curl -o shell.tgz https://downloads.mongodb.com/compass/mongosh-2.2.10-linux-x64.tgz
  #     tar xvf shell.tgz
  #   command: export PATH=$PATH/workspace/gitpod_sample_python/mongosh-2.2.10-linux-x64/mongosh
  
  - name: atlas shell
    init: brew install mongodb-atlas

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-browser

  - name: dbpath
    port: 27017

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - ms-toolsai.jupyterdocs/introduction/getting-started/quickstart
    - mongodb.mongodb-vscode
